const Category    = require("./Category")
const Subcategory = require("./Subcategory")
const Brand       = require("./Brand")
const Product     = require("./Product")
const User        = require("./User")
const Auth        = require("./Auth")
const Review      = require("./Review")
const Wishlist    = require("./Wishlist")
const Addresses   = require("./Addresses")
const Coupon      = require("./Coupon")
const Cart        = require("./Cart")
const Order       = require("./Order")

exports. mountenRoutes = (app)=>{
    app.use("/api/v1/category"    , Category)
    app.use("/api/v1/subcategory" , Subcategory)
    app.use("/api/v1/brand"       , Brand)
    app.use("/api/v1/product"     , Product)
    app.use("/api/v1/user"        , User)
    app.use("/api/v1/auth"        , Auth)
    app.use("/api/v1/review"      , Review)
    app.use("/api/v1/wishlist"    , Wishlist)
    app.use("/api/v1/addresses"   , Addresses)
    app.use("/api/v1/coupon"      , Coupon)
    app.use("/api/v1/cart"        , Cart)
    app.use("/api/v1/order"       , Order)
} 